import { describe, expect, it } from "vitest";
import { CodexAppServerSession, AppServerProtocolError, type AppServerNotification, type AppServerRequest, type AppServerTransport } from "./index.js";

class FakeTransport implements AppServerTransport {
  requests: Array<{ method: string; params: Record<string, unknown> }> = []; responses: Array<{ id: string | number; result: Record<string, unknown> }> = []; notifications: Array<(m: AppServerNotification) => void> = []; serverRequests: Array<(m: AppServerRequest) => void> = []; crashes: Array<(e: Error) => void> = []; reconnected = false;
  async request(method: string, params: Record<string, unknown>): Promise<unknown> { this.requests.push({ method, params }); if (method === "initialize") return { userAgent: "codex-cli", codexHome: "/tmp", platformFamily: "unix", platformOs: "macos" }; if (method === "thread/start") return { thread: { id: "thread-1" } }; if (method === "turn/start") return { turn: { id: "turn-1" } }; return {}; }
  async respond(id: string | number, result: Record<string, unknown>): Promise<void> { this.responses.push({ id, result }); }
  onNotification(l: (m: AppServerNotification) => void): void { this.notifications.push(l); } onRequest(l: (m: AppServerRequest) => void): void { this.serverRequests.push(l); } onCrash(l: (e: Error) => void): void { this.crashes.push(l); } async reconnect(): Promise<void> { this.reconnected = true; } async close(): Promise<void> {}
  notify(m: AppServerNotification): void { this.notifications.forEach((l) => l(m)); } serverRequest(m: AppServerRequest): void { this.serverRequests.forEach((l) => l(m)); } crash(): void { this.crashes.forEach((l) => l(new Error("lost"))); }
}
const session = (transport: FakeTransport) => new CodexAppServerSession(transport, { clientName: "notdone", clientVersion: "1", workspaceRoot: "/workspace", approve: async () => "decline" });
describe("Codex App Server session adapter", () => {
  it("handshakes, starts/resumes turns, maps progress/diff, and persists session references", async () => { const t = new FakeTransport(); const s = session(t); await s.initialize(); expect(await s.start("prompt")).toMatchObject({ backendId: "codex-app-server", sessionId: "thread-1" }); await s.resume("thread-1", "again"); t.notify({ method: "turn/diff/updated", params: { threadId: "thread-1", turnId: "turn-1", diff: "@@" } }); t.notify({ method: "future/event", params: {} }); expect(s.events).toMatchObject([{ type: "diff", detail: "@@" }, { type: "unknown" }]); await s.reconnect(); expect(t.reconnected).toBe(true); });
  it("forwards approval decisions and supports cancellation/crash events", async () => { const t = new FakeTransport(); const s = session(t); await s.start("prompt"); t.serverRequest({ id: 1, method: "item/commandExecution/requestApproval", params: {} }); await new Promise((r) => setTimeout(r, 0)); expect(t.responses).toEqual([{ id: 1, result: { decision: "decline" } }]); await s.cancel("turn-1"); t.crash(); expect(s.events.at(-1)).toMatchObject({ type: "crash" }); });
  it("rejects malformed handshake and unavailable resume", async () => { const t = new FakeTransport(); t.request = async () => ({}); await expect(session(t).initialize()).rejects.toBeInstanceOf(AppServerProtocolError); await expect(session(new FakeTransport()).reconnect()).rejects.toBeInstanceOf(AppServerProtocolError); });
  it("rejects a server version outside the configured compatibility prefix", async () => { const t = new FakeTransport(); const s = new CodexAppServerSession(t, { clientName: "notdone", clientVersion: "1", workspaceRoot: "/workspace", expectedUserAgentPrefix: "codex-cli 999", approve: async () => "decline" }); await expect(s.initialize()).rejects.toThrow("incompatible"); });
});
